name: CI
on:
  push:
    branches: [main]
jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
      - name: Saludar
        run: echo "Hola desde GitHub Actions"
